import { notFound } from "next/navigation";
import { TestingPageHeader } from "../../testing-page-header";
import { TestingBackNavigation } from "../../testing-back-navigation";
import { ImageLightbox } from "@/components/application/media/image-lightbox";
import { VideoLightbox } from "@/components/application/media/video-lightbox";
import { AdTypeChip } from "@/components/application/media/ad-type-chip";
import { testingPeriodInput } from "@/lib/testing-google";
import { getRedditTestingData, type RedditAd } from "@/lib/testing-reddit";

const currency=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2});const decimal=new Intl.NumberFormat("en-US",{maximumFractionDigits:2});const percent=new Intl.NumberFormat("en-US",{style:"percent",minimumFractionDigits:2,maximumFractionDigits:2});
const awareness=[{key:"ctr",label:"CTR",format:"percent"},{key:"cpm",label:"CPM",format:"currency"},{key:"costPerThousandReach",label:"Cost / 1K reach",format:"currency"},{key:"spend",label:"Spend",format:"currency"}];const conversion=[{key:"cpa",label:"CPA",format:"currency"},{key:"cvr",label:"CVR",format:"percent"},{key:"roas",label:"ROAS",format:"roas"},{key:"orders",label:"Orders",format:"decimal"},{key:"revenue",label:"Revenue",format:"currency"},{key:"spend",label:"Spend",format:"currency"},{key:"ctr",label:"CTR",format:"percent"},{key:"cpc",label:"CPC",format:"currency"},{key:"cpm",label:"CPM",format:"currency"}] as const;
function value(input:number|null,format:string){if(input==null||!Number.isFinite(input))return "—";if(format==="percent")return percent.format(input);if(format==="roas")return input.toFixed(2);if(format==="decimal")return decimal.format(input);return currency.format(input);}
function AdIdentity({ad}:{ad:RedditAd}){return <div className="flex min-w-0 items-start gap-3">{ad.contentType==="Video"&&ad.videoUrl?<VideoLightbox src={ad.videoUrl} thumbnailUrl={ad.thumbnailUrl} title={ad.name}/>:<ImageLightbox src={ad.thumbnailUrl} alt={ad.name} size="lg"/>}<div className="min-w-0"><p className="break-words text-body-medium text-text-primary">{ad.name}</p>{ad.headline&&<p className="mt-1 break-words text-body-2-medium text-text-secondary">{ad.headline}</p>}<AdTypeChip className="mt-2" type={ad.contentType}/>{ad.body&&<details className="group mt-3"><summary className="cursor-pointer select-none text-body-2-medium text-button-ghost-foreground">View ad copy</summary><div className="mt-2 whitespace-pre-wrap rounded-xl bg-background-secondary-default p-3 text-body-2-regular text-text-secondary">{ad.body}</div></details>}</div></div>;}
type SearchParams={period?:string|string[];start?:string|string[];end?:string|string[]};
export default async function RedditGroupPage({params,searchParams}:{params:Promise<{group:string}>;searchParams:Promise<SearchParams>}){const route=await params,query=await searchParams,data=await getRedditTestingData(testingPeriodInput(query));const campaign=data.campaigns.find(item=>item.groups.some(group=>group.adGroupId===route.group));const group=campaign?.groups.find(item=>item.adGroupId===route.group);if(!campaign||!group)notFound();const backQuery=new URLSearchParams();for(const [key,raw] of Object.entries(query)){const item=Array.isArray(raw)?raw[0]:raw;if(item)backQuery.set(key,item);}const metrics=campaign.kind==="Awareness"?awareness:conversion;return <><TestingPageHeader section="Reddit" title={group.name} description={campaign.name}/><TestingBackNavigation platform="Reddit" platformHref="/bluevua/testing/reddit" query={backQuery.toString()}/><section className="overflow-hidden rounded-3xl border border-border-button-default bg-background-primary-default shadow-card"><div className="border-b border-border-table p-5"><h2 className="text-title-3-semibold text-text-primary">Active Ads and Creative Performance</h2><p className="mt-1 text-body-regular text-text-secondary">{data.periodLabel} · {group.activeAds.length} active ads</p></div>{group.activeAds.map(ad=><article key={ad.adId} className="grid gap-5 border-b border-border-table p-5 last:border-0 hover:bg-background-primary-hover lg:grid-cols-[minmax(280px,2fr)_minmax(480px,3fr)] lg:items-center"><AdIdentity ad={ad}/><dl className={`grid grid-cols-2 gap-x-4 gap-y-3 ${campaign.kind==="Awareness"?"sm:grid-cols-4":"sm:grid-cols-5"}`}>{metrics.map(item=><div key={item.key}><dt className="text-caption-1-semibold text-text-tertiary">{item.label}</dt><dd className="mt-1 text-body-medium tabular-nums text-text-primary">{value(ad[item.key as keyof RedditAd] as number|null,item.format)}</dd></div>)}</dl></article>)}</section></>;}
