import "server-only";
import { Pool, type PoolClient } from "pg";
import { AI_PROMPT_VERSION, ANALYTICS_VERSION } from "./klaviyo-analytics";

export type DateRange = { start: string; end: string };
export type DashboardRequest = { range: DateRange; comparison: DateRange; presetLabel: string; comparisonLabel: string; language?:"en"|"zh" };
export type AiInsightItem = { title:string; observation:string; interpretation:string; supporting_evidence:string[]; driver:string; business_implication:string; next_step:string; confidence:"high"|"medium"|"low" };
export type AiInsightPayload = { headline:string; executive_summary:string; performance_status:"positive"|"mixed"|"negative"|"stable"; key_insights:AiInsightItem[]; recommended_actions:Array<{action:string;reason:string;priority:"high"|"medium"|"low"}> };
export type CampaignMetric = { id:string; name:string; sentDate:string; channel:"email"|"sms"; messageId:string; revenue:number; recipients:number; delivered:number; openRate:number; clickRate:number; orders:number; aov:number };
export type DashboardData = {
  timezone:string; range:DateRange; comparison:DateRange; presetLabel:string; comparisonLabel:string; dataUpdatedThrough:string;
  totals:{storeRevenue:number;edmRevenue:number;emailRevenue:number;smsRevenue:number;flowRevenue:number;campaignRevenue:number;recipients:number;emailRecipients:number;smsRecipients:number};
  previous:DashboardData["totals"];
  health:{unsubscribeRate:number;spamRate:number;bounceRate:number;previousUnsubscribeRate:number;previousSpamRate:number;previousBounceRate:number;dates:string[];unsubscribe:number[];spam:number[];bounce:number[]};
  subscribers:{emailInventory:number;smsInventory:number;previousEmailInventory:number;previousSmsInventory:number;emailSubscribers:number;smsSubscribers:number;emailUnsubscribers:number;smsUnsubscribers:number;previousEmailSubscribers:number;previousSmsSubscribers:number;previousEmailUnsubscribers:number;previousSmsUnsubscribers:number;dates:string[];emailNew:number[];emailLost:number[];smsNew:number[];smsLost:number[]};
  flows:Array<{name:string;revenue:number;previousRevenue:number}>; emailCampaigns:CampaignMetric[]; smsCampaigns:CampaignMetric[];
  abTests:Array<{campaign:string;variations:Array<{name:string;openRate:number;clickRate:number;revenue:number;aov:number}>;winner:string;winningOpenRate:number;lift:number|null}>;
};

export class KlaviyoError extends Error { constructor(message:string,public retryAfter=0){super(message)} }

declare global { var klaviyoDashboardPool: Pool | undefined }
function createPool(){const connectionString=process.env.KLAVIYO_DATABASE_URL?.trim();if(!connectionString)throw new KlaviyoError("KLAVIYO_DATABASE_URL is not configured.");return new Pool({connectionString,ssl:{rejectUnauthorized:false},max:8,idleTimeoutMillis:30_000,connectionTimeoutMillis:12_000})}
const db=globalThis.klaviyoDashboardPool??createPool();
if(process.env.NODE_ENV!=="production")globalThis.klaviyoDashboardPool=db;

const TIMEZONE="US/Eastern";
const n=(value:unknown)=>Number(value||0);
const day=(value:unknown)=>value instanceof Date?value.toISOString().slice(0,10):String(value||"").slice(0,10);
export async function accountTimezone(){return TIMEZONE}
export function accountToday(timezone:string){const values=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const map=Object.fromEntries(values.map(item=>[item.type,item.value]));return `${map.year}-${map.month}-${map.day}`}

type DailyRow={metric_name:string;date:string|Date;count_value:string|number|null;unique_value:string|number|null;sum_value:string|number|null};
type ReportRow={campaign_message_id?:string;campaign_id?:string;campaign_name?:string;campaign_message_name?:string;send_channel?:string;variation?:string;variation_name?:string;sent_date?:string|Date;flow_id?:string;flow_name?:string;recipients:string|number|null;delivered:string|number|null;opens_unique:string|number|null;clicks_unique:string|number|null;conversions:string|number|null;conversion_uniques:string|number|null;conversion_value:string|number|null;bounced:string|number|null;unsubscribe_uniques:string|number|null;spam_complaints:string|number|null};

async function daily(client:PoolClient,range:DateRange){const result=await client.query<DailyRow>(`select metric_name,date,count_value,unique_value,sum_value from fact_metric_daily where date between $1::date and $2::date order by date`,[range.start,range.end]);return result.rows}
async function campaignReport(client:PoolClient,range:DateRange){const result=await client.query<ReportRow>(`select p.*,c.campaign_name,coalesce(m.campaign_message_name,c.campaign_name,p.campaign_id) campaign_message_name,p.send_date sent_date from fact_campaign_performance p left join dim_campaign c on c.campaign_id=p.campaign_id left join dim_campaign_message m on m.campaign_message_id=p.campaign_message_id where p.send_date between $1::date and $2::date`,[range.start,range.end]);return result.rows}
async function flowReport(client:PoolClient,range:DateRange){const result=await client.query<ReportRow>(`select p.*,coalesce(f.flow_name,m.flow_name,p.flow_id) flow_name from fact_flow_daily p left join dim_flow f on f.flow_id=p.flow_id left join dim_flow_message m on m.flow_message_id=p.flow_message_id where p.date between $1::date and $2::date`,[range.start,range.end]);return result.rows}
function metric(rows:DailyRow[],name:string,column:"count_value"|"unique_value"|"sum_value"="count_value"){return rows.filter(row=>row.metric_name===name).reduce((sum,row)=>sum+n(row[column]),0)}
function series(rows:DailyRow[],name:string,column:"count_value"|"unique_value"="count_value",dates:string[]){const values=new Map(rows.filter(row=>row.metric_name===name).map(row=>[day(row.date),n(row[column])]));return dates.map(date=>values.get(date)||0)}
function datesBetween(range:DateRange){const out:string[]=[];for(let cursor=new Date(`${range.start}T00:00:00Z`),end=new Date(`${range.end}T00:00:00Z`);cursor<=end;cursor.setUTCDate(cursor.getUTCDate()+1))out.push(cursor.toISOString().slice(0,10));return out}
function reportTotals(rows:ReportRow[],channel?:string){const selected=rows.filter(row=>!channel||String(row.send_channel||"").toLowerCase()===channel);const sum=(key:keyof ReportRow)=>selected.reduce((total,row)=>total+n(row[key]),0);const delivered=sum("delivered"),revenue=sum("conversion_value"),conversions=sum("conversions");return{recipients:sum("recipients"),delivered,revenue,conversions,aov:conversions?revenue/conversions:0,openRate:sum("opens_unique")/Math.max(delivered,1),clickRate:sum("clicks_unique")/Math.max(delivered,1),unsubscribeRate:sum("unsubscribe_uniques")/Math.max(delivered,1),bounceRate:sum("bounced")/Math.max(sum("recipients"),1),spamRate:sum("spam_complaints")/Math.max(delivered,1)}}
function nativeHealth(rows:DailyRow[],dates:string[]){const received=series(rows,"Received Email","count_value",dates),unsub=series(rows,"Unsubscribed from Email Marketing","unique_value",dates),spam=series(rows,"Marked Email as Spam","count_value",dates),bounce=series(rows,"Bounced Email","count_value",dates);const rate=(values:number[])=>values.map((value,index)=>value/Math.max(received[index],1));const total=received.reduce((a,b)=>a+b,0);return{unsubscribeRate:unsub.reduce((a,b)=>a+b,0)/Math.max(total,1),spamRate:spam.reduce((a,b)=>a+b,0)/Math.max(total,1),bounceRate:bounce.reduce((a,b)=>a+b,0)/Math.max(total,1),unsubscribe:rate(unsub),spam:rate(spam),bounce:rate(bounce)}}
function totals(dailyRows:DailyRow[],campaignRows:ReportRow[],flowRows:ReportRow[]){const email=reportTotals([...campaignRows,...flowRows],"email"),sms=reportTotals([...campaignRows,...flowRows],"sms"),flow=reportTotals(flowRows);return{storeRevenue:metric(dailyRows,"Placed Order","sum_value"),edmRevenue:email.revenue+sms.revenue,emailRevenue:email.revenue,smsRevenue:sms.revenue,flowRevenue:flow.revenue,campaignRevenue:reportTotals(campaignRows,"email").revenue,recipients:metric(dailyRows,"Received Email")+metric(dailyRows,"Sent Text Message"),emailRecipients:metric(dailyRows,"Received Email"),smsRecipients:metric(dailyRows,"Sent Text Message")}}
function flowRevenue(rows:ReportRow[],aliases:string[],channel:string|null){return rows.reduce((sum,row)=>{const name=String(row.flow_name||"").toLowerCase(),send=String(row.send_channel||"").toLowerCase();return(channel===null||send===channel)&&aliases.some(alias=>name.includes(alias))?sum+n(row.conversion_value):sum},0)}
function flowCards(current:ReportRow[],previous:ReportRow[]){const definitions:[string,string[],string|null][]=[["Welcome Flow",["welcome"],null],["SMS Welcome Flow",["welcome"],"sms"],["Abandoned Checkout Flow",["abandoned checkout","checkout abandon"],"email"],["Abandoned Cart Flow",["abandoned cart","cart abandon"],"email"],["Post Purchase Flow",["post purchase","post-purchase","instructions","reminders"],"email"]];return definitions.map(([name,aliases,channel])=>({name,revenue:flowRevenue(current,aliases,channel),previousRevenue:flowRevenue(previous,aliases,channel)}))}
function campaigns(rows:ReportRow[],channel:"email"|"sms"){const grouped=new Map<string,CampaignMetric&{opensUnique:number;clicksUnique:number}>();for(const row of rows){if(String(row.send_channel||"").toLowerCase()!==channel)continue;const id=String(row.campaign_id||row.campaign_message_id||"");const item=grouped.get(id)||{id,name:String(row.campaign_name||row.campaign_message_name||id),sentDate:day(row.sent_date),channel,messageId:String(row.campaign_message_id||""),revenue:0,recipients:0,delivered:0,openRate:0,clickRate:0,orders:0,aov:0,opensUnique:0,clicksUnique:0};item.revenue+=n(row.conversion_value);item.recipients+=n(row.recipients);item.delivered+=n(row.delivered);item.orders+=n(row.conversions);item.opensUnique+=n(row.opens_unique);item.clicksUnique+=n(row.clicks_unique);grouped.set(id,item)}return[...grouped.values()].map(({opensUnique,clicksUnique,...item})=>({...item,openRate:opensUnique/Math.max(item.delivered,1),clickRate:clicksUnique/Math.max(item.delivered,1),aov:item.orders?item.revenue/item.orders:0})).sort((a,b)=>b.sentDate.localeCompare(a.sentDate))}
function abTests(rows:ReportRow[]){const grouped=new Map<string,ReportRow[]>();for(const row of rows){if(!row.variation&&!row.variation_name)continue;const key=String(row.campaign_name||row.campaign_message_name||row.campaign_id||"Campaign"),items=grouped.get(key)||[];items.push(row);grouped.set(key,items)}return[...grouped].map(([campaign,items])=>{const variations=items.sort((a,b)=>String(a.variation||a.variation_name).localeCompare(String(b.variation||b.variation_name))).map((row,index)=>({name:`Variation ${String.fromCharCode(65+index)}`,openRate:n(row.opens_unique)/Math.max(n(row.delivered),1),clickRate:n(row.clicks_unique)/Math.max(n(row.delivered),1),revenue:n(row.conversion_value),aov:n(row.conversions)?n(row.conversion_value)/n(row.conversions):0}));const ranked=[...variations].sort((a,b)=>b.openRate-a.openRate||b.clickRate-a.clickRate||b.revenue-a.revenue),winner=ranked[0],runner=ranked[1];return{campaign,variations,winner:winner?.name||"—",winningOpenRate:winner?.openRate||0,lift:runner?.openRate?(winner.openRate-runner.openRate)/runner.openRate:null}})}

async function inventory(client:PoolClient,end:string){const result=await client.query<{date:string|Date;email_subscribers:string|number;sms_subscribers:string|number}>(`select date,email_subscribers,sms_subscribers from fact_subscriber_daily where date<=$1::date order by date desc limit 1`,[end]);return{email:n(result.rows[0]?.email_subscribers),sms:n(result.rows[0]?.sms_subscribers)}}
async function freshness(client:PoolClient){const result=await client.query<{latest:string|Date}>(`select greatest(coalesce((select max(date) from fact_metric_daily),'1900-01-01'::date),coalesce((select max(date) from fact_subscriber_daily),'1900-01-01'::date),coalesce((select max(date) from fact_email_link_daily),'1900-01-01'::date)) latest`);return day(result.rows[0]?.latest)}
export async function dataUpdatedThrough(){const client=await db.connect();try{return await freshness(client)}finally{client.release()}}

export async function loadDashboard(input:DashboardRequest):Promise<DashboardData>{const client=await db.connect();try{await client.query("begin transaction read only");const currentDaily=await daily(client,input.range),previousDaily=await daily(client,input.comparison),currentCampaign=await campaignReport(client,input.range),previousCampaign=await campaignReport(client,input.comparison),currentFlow=await flowReport(client,input.range),previousFlow=await flowReport(client,input.comparison),subscriberInventory=await inventory(client,input.range.end),previousSubscriberInventory=await inventory(client,input.comparison.end),dataUpdatedThrough=await freshness(client);await client.query("commit");const dates=datesBetween(input.range),currentHealth=nativeHealth(currentDaily,dates),previousHealth=nativeHealth(previousDaily,datesBetween(input.comparison));return{timezone:TIMEZONE,range:input.range,comparison:input.comparison,presetLabel:input.presetLabel,comparisonLabel:input.comparisonLabel,dataUpdatedThrough,totals:totals(currentDaily,currentCampaign,currentFlow),previous:totals(previousDaily,previousCampaign,previousFlow),health:{...currentHealth,previousUnsubscribeRate:previousHealth.unsubscribeRate,previousSpamRate:previousHealth.spamRate,previousBounceRate:previousHealth.bounceRate,dates},subscribers:{emailInventory:subscriberInventory.email,smsInventory:subscriberInventory.sms,previousEmailInventory:previousSubscriberInventory.email,previousSmsInventory:previousSubscriberInventory.sms,emailSubscribers:metric(currentDaily,"Subscribed to Email Marketing"),smsSubscribers:metric(currentDaily,"Subscribed to Text Messaging Marketing"),emailUnsubscribers:metric(currentDaily,"Unsubscribed from Email Marketing","unique_value"),smsUnsubscribers:metric(currentDaily,"Unsubscribed from Text Messaging Marketing","unique_value"),previousEmailSubscribers:metric(previousDaily,"Subscribed to Email Marketing"),previousSmsSubscribers:metric(previousDaily,"Subscribed to Text Messaging Marketing"),previousEmailUnsubscribers:metric(previousDaily,"Unsubscribed from Email Marketing","unique_value"),previousSmsUnsubscribers:metric(previousDaily,"Unsubscribed from Text Messaging Marketing","unique_value"),dates,emailNew:series(currentDaily,"Subscribed to Email Marketing","count_value",dates),emailLost:series(currentDaily,"Unsubscribed from Email Marketing","unique_value",dates),smsNew:series(currentDaily,"Subscribed to Text Messaging Marketing","count_value",dates),smsLost:series(currentDaily,"Unsubscribed from Text Messaging Marketing","unique_value",dates)},flows:flowCards(currentFlow,previousFlow),emailCampaigns:campaigns(currentCampaign,"email"),smsCampaigns:campaigns(currentCampaign,"sms"),abTests:abTests(currentCampaign)}}catch(error){await client.query("rollback").catch(()=>{});throw new KlaviyoError(error instanceof Error?`Klaviyo database: ${error.message}`:"Klaviyo database query failed.")}finally{client.release()}}

function previousYear(value:string){const [year,month,rawDay]=value.split("-").map(Number),safeDay=month===2&&rawDay===29?28:rawDay;return`${year-1}-${String(month).padStart(2,"0")}-${String(safeDay).padStart(2,"0")}`}
export async function loadYoY(range:DateRange){const yoy={start:previousYear(range.start),end:previousYear(range.end)},client=await db.connect();try{const dailyRows=await daily(client,yoy),campaignRows=await campaignReport(client,yoy),flowRows=await flowReport(client,yoy),all=totals(dailyRows,campaignRows,flowRows),health=nativeHealth(dailyRows,datesBetween(yoy)),subscriberInventory=await inventory(client,yoy.end);return{range:yoy,...all,emailInventory:subscriberInventory.email,smsInventory:subscriberInventory.sms,emailSubscribers:metric(dailyRows,"Subscribed to Email Marketing"),smsSubscribers:metric(dailyRows,"Subscribed to Text Messaging Marketing"),emailUnsubscribers:metric(dailyRows,"Unsubscribed from Email Marketing","unique_value"),smsUnsubscribers:metric(dailyRows,"Unsubscribed from Text Messaging Marketing","unique_value"),unsubscribeRate:health.unsubscribeRate,spamRate:health.spamRate,bounceRate:health.bounceRate,flowValues:Object.fromEntries(flowCards(flowRows,[]).map(item=>[item.name,item.revenue]))}}catch(error){throw new KlaviyoError(error instanceof Error?`Klaviyo database: ${error.message}`:"Previous Year data could not be loaded.")}finally{client.release()}}

type AiDetailRow={id:string;name:string;parent_id:string;parent_name:string;send_channel:string;recipients:string|number;delivered:string|number;opens_unique:string|number;clicks_unique:string|number;conversions:string|number;conversion_value:string|number;bounced:string|number;unsubscribe_uniques:string|number;spam_complaints:string|number};
function aiRows(rows:AiDetailRow[]){return rows.map(row=>({id:row.id,name:row.name,parentId:row.parent_id,parentName:row.parent_name,channel:String(row.send_channel||"").toLowerCase(),recipients:n(row.recipients),delivered:n(row.delivered),opens:n(row.opens_unique),clicks:n(row.clicks_unique),conversions:n(row.conversions),revenue:n(row.conversion_value),bounced:n(row.bounced),unsubscribes:n(row.unsubscribe_uniques),spam:n(row.spam_complaints)}))}
export async function loadAiDetails(input:DashboardRequest){const client=await db.connect();try{await client.query("begin transaction read only");const flowQuery=`select p.flow_message_id id,p.flow_id parent_id,coalesce(m.message_name,m.flow_name,f.flow_name,p.flow_message_id) name,coalesce(m.flow_name,f.flow_name,p.flow_id) parent_name,p.send_channel,sum(p.recipients) recipients,sum(p.delivered) delivered,sum(p.opens_unique) opens_unique,sum(p.clicks_unique) clicks_unique,sum(p.conversions) conversions,sum(p.conversion_value) conversion_value,sum(p.bounced) bounced,sum(p.unsubscribe_uniques) unsubscribe_uniques,sum(p.spam_complaints) spam_complaints from fact_flow_daily p left join dim_flow_message m on m.flow_message_id=p.flow_message_id left join dim_flow f on f.flow_id=p.flow_id where p.date between $1::date and $2::date group by p.flow_message_id,m.message_name,m.flow_name,f.flow_name,p.flow_id,p.send_channel`;const campaignQuery=`select p.campaign_message_id id,p.campaign_id parent_id,coalesce(m.campaign_message_name,c.campaign_name,p.campaign_message_id) name,coalesce(c.campaign_name,p.campaign_id) parent_name,p.send_channel,sum(p.recipients) recipients,sum(p.delivered) delivered,sum(p.opens_unique) opens_unique,sum(p.clicks_unique) clicks_unique,sum(p.conversions) conversions,sum(p.conversion_value) conversion_value,sum(p.bounced) bounced,sum(p.unsubscribe_uniques) unsubscribe_uniques,sum(p.spam_complaints) spam_complaints from fact_campaign_performance p left join dim_campaign_message m on m.campaign_message_id=p.campaign_message_id left join dim_campaign c on c.campaign_id=p.campaign_id where p.send_date between $1::date and $2::date group by p.campaign_message_id,m.campaign_message_name,c.campaign_name,p.campaign_id,p.send_channel`;const currentFlows=await client.query<AiDetailRow>(flowQuery,[input.range.start,input.range.end]);const previousFlows=await client.query<AiDetailRow>(flowQuery,[input.comparison.start,input.comparison.end]);const currentCampaigns=await client.query<AiDetailRow>(campaignQuery,[input.range.start,input.range.end]);const previousCampaigns=await client.query<AiDetailRow>(campaignQuery,[input.comparison.start,input.comparison.end]);await client.query("commit");return{flowMessages:{current:aiRows(currentFlows.rows),comparison:aiRows(previousFlows.rows)},campaignMessages:{current:aiRows(currentCampaigns.rows),comparison:aiRows(previousCampaigns.rows)}}}catch(error){await client.query("rollback").catch(()=>{});throw new KlaviyoError(error instanceof Error?`Klaviyo database: ${error.message}`:"AI detail query failed.")}finally{client.release()}}

const insightPreset=(label:string)=>label==="Last Week (Tue–Mon)"?"last_week":null;
async function insightKey(input:DashboardRequest){const result=await db.query<{version:string}>(`select concat(greatest(coalesce((select max(send_date) from fact_campaign_performance),'1900-01-01'::date),coalesce((select max(date) from fact_flow_daily),'1900-01-01'::date),coalesce((select max(date) from fact_metric_daily),'1900-01-01'::date)),'|',coalesce((select max(updated_at) from fact_campaign_performance),'1900-01-01'::timestamptz),'|',coalesce((select max(updated_at) from fact_flow_daily),'1900-01-01'::timestamptz)) version`);return`${insightPreset(input.presetLabel)}:${input.language||"en"}:${input.range.start}:${input.range.end}:${input.comparison.start}:${input.comparison.end}:${ANALYTICS_VERSION}:${AI_PROMPT_VERSION}:${process.env.model||process.env.OPENROUTER_MODEL||"model"}:${result.rows[0]?.version}`}
export async function cachedAiInsight(input:DashboardRequest){const preset=insightPreset(input.presetLabel);if(!preset)return null;const result=await db.query<{payload:AiInsightPayload;model:string;generated_at:string|Date}>(`select payload,model,generated_at from ai_insight_cache where cache_key=$1 and expires_at>now() limit 1`,[await insightKey(input)]);const row=result.rows[0];return row?{insights:row.payload,model:row.model,generatedAt:new Date(row.generated_at).toISOString()}:null}
export async function saveAiInsight(input:DashboardRequest,payload:AiInsightPayload,model:string){const preset=insightPreset(input.presetLabel);if(!preset)return;await db.query(`insert into ai_insight_cache(cache_key,preset,range_start,range_end,comparison_start,comparison_end,payload,model,generated_at,expires_at) values($1,$2,$3::date,$4::date,$5::date,$6::date,$7::jsonb,$8,now(),now()+interval '8 days') on conflict(cache_key) do update set payload=excluded.payload,model=excluded.model,generated_at=excluded.generated_at,expires_at=excluded.expires_at`,[await insightKey(input),preset,input.range.start,input.range.end,input.comparison.start,input.comparison.end,JSON.stringify(payload),model])}
export async function clearAiInsightPreset(preset:"last_30_days"|"last_week",keepRangeEnd?:string){if(keepRangeEnd)await db.query(`delete from ai_insight_cache where preset=$1 and range_end<>$2::date`,[preset,keepRangeEnd]);else await db.query(`delete from ai_insight_cache where preset=$1`,[preset])}

export async function campaignPreview(messageId:string,channel:"email"|"sms"){const result=await db.query<{image_url:string|null;alt_text:string|null}>(`select coalesce(a.image_url,c.image_url) image_url,coalesce(a.alt_text,c.alt_text) alt_text from dim_campaign_message m join dim_email_creative c on c.template_id=m.template_id left join dim_creative_asset a on a.asset_id=c.asset_id where m.campaign_message_id=$1 and coalesce(a.image_url,c.image_url) is not null order by c.block_id limit 30`,[messageId]);const images=result.rows.filter(row=>row.image_url);if(channel==="sms")return{type:"sms",body:"",mediaUrl:images[0]?.image_url||""};const html=`<!doctype html><html><body style="margin:0;background:#f5f5f5;font-family:Arial,sans-serif"><main style="max-width:680px;margin:auto;background:white">${images.map(row=>`<img src="${escapeHtml(row.image_url||"")}" alt="${escapeHtml(row.alt_text||"")}" style="display:block;width:100%;height:auto">`).join("")}</main></body></html>`;return{type:"email",imageUrl:images[0]?.image_url||null,html}}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]||char))}

export async function creativePerformance(range:DateRange){const result=await db.query<{campaign:string;sent_date:string|Date;source_message_id:string;link_url:string;unique_clicks:string|number;delivered:string|number;image_url:string|null}>(`select coalesce(c.campaign_name,m.campaign_message_name,l.source_message_id) campaign,p.send_date sent_date,l.source_message_id,l.link_url,sum(l.unique_clicks) unique_clicks,max(p.delivered) delivered,max(coalesce(a.image_url,ec.image_url)) image_url from fact_email_link_daily l left join dim_campaign_message m on m.campaign_message_id=l.campaign_message_id left join dim_campaign c on c.campaign_id=coalesce(l.campaign_id,m.campaign_id) left join fact_campaign_performance p on p.campaign_message_id=l.campaign_message_id left join dim_email_creative ec on ec.template_id=m.template_id and ec.destination_url=l.link_url left join dim_creative_asset a on a.asset_id=ec.asset_id where l.source_type='campaign' and l.date between $1::date and $2::date group by c.campaign_name,m.campaign_message_name,l.source_message_id,l.link_url,p.send_date order by p.send_date desc,l.source_message_id,l.link_url`,[range.start,range.end]);const raw=result.rows.map((row,index)=>({campaign:row.campaign,sentDate:day(row.sent_date),sourceMessageId:row.source_message_id,url:row.link_url,clicks:n(row.unique_clicks),delivered:n(row.delivered),imageUrl:row.image_url,order:index})),unique=new Map<string,(typeof raw)[number]>();for(const item of raw){const key=`${item.campaign}\u0000${item.url}`,current=unique.get(key);if(current){current.clicks+=item.clicks;current.delivered+=item.delivered;current.imageUrl ||= item.imageUrl;if(item.sentDate>current.sentDate)current.sentDate=item.sentDate}else unique.set(key,{...item})}const records=[...unique.values()].map(item=>({...item,rate:item.clicks/Math.max(item.delivered,1)})),grouped=new Map<string,typeof records>();for(const item of records){const list=grouped.get(item.campaign)||[];list.push(item);grouped.set(item.campaign,list)}return{campaigns:[...grouped].map(([campaign,modules])=>({campaign,sentDate:modules.reduce((latest,item)=>item.sentDate>latest?item.sentDate:latest,""),imageUrl:modules.find(item=>item.imageUrl)?.imageUrl||null,modules:modules.sort((a,b)=>b.rate-a.rate)})),top:[...records].sort((a,b)=>b.rate-a.rate).slice(0,10)}}
