import assert from "node:assert/strict";
import test from "node:test";
import { buildAnalysisPayload, buildDeterministicInsight, isAiInsightPayload, parseAiInsightResponse } from "./klaviyo-analytics.ts";

const entity=(id:string,parentId:string,revenue:number,recipients:number,delivered:number,opens:number,clicks:number,conversions:number)=>({id,name:id,parentId,parentName:parentId,channel:"email",revenue,recipients,delivered,opens,clicks,conversions});
const data:any={range:{start:"2026-09-08",end:"2026-09-14"},comparison:{start:"2026-09-01",end:"2026-09-07"},comparisonLabel:"Previous period",timezone:"US/Eastern",dataUpdatedThrough:"2026-09-14",totals:{emailRecipients:0},health:{bounceRate:.01,previousBounceRate:.02,unsubscribeRate:.003,previousUnsubscribeRate:.003,spamRate:.001,previousSpamRate:.001}};
const details:any={campaignMessages:{current:[entity("campaign-a","campaign",200,120,100,50,10,4)],comparison:[entity("campaign-a","campaign",100,100,90,36,9,2),entity("campaign-b","campaign",50,50,45,20,5,1)]},flowMessages:{current:[entity("flow-a","flow",400,200,180,90,18,8)],comparison:[entity("flow-a","flow",600,200,180,90,18,12)]}};

test("period comparison and hierarchy do not double count",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(payload.executive.edm_revenue.current,600);assert.equal(payload.executive.edm_revenue.previous,750);assert.equal(payload.executive.edm_revenue.absolute_delta,-150);assert.equal(payload.executive.campaign_revenue.current,200);assert.equal(payload.executive.flow_revenue.current,400)});
test("uses consistent Klaviyo denominators",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(payload.funnel.email.open_rate.current_rate,140/280);assert.equal(payload.funnel.email.click_rate.current_rate,28/280);assert.equal(payload.funnel.email.conversion_rate.current_rate,12/320);assert.equal(payload.funnel.email.orders_per_recipient.current,12/320)});
test("division by zero is safe",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(payload.funnel.sms.open_rate.current_rate,null);assert.equal(payload.funnel.sms.revenue_per_click.current,0)});
test("drivers rank by absolute revenue delta and calculate signed contribution",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(payload.drivers.message_decliners[0].name,"flow-a");assert.equal(payload.drivers.message_decliners[0].revenue_delta,-200);assert.equal(payload.drivers.message_decliners[0].delta_contribution_pct,200/150);assert.equal(payload.drivers.message_gainers[0].name,"campaign-a")});
test("diagnostic thresholds create deterministic signals",()=>{const payload:any=buildAnalysisPayload(data,details);assert.ok(payload.diagnostic_signals.includes("revenue_efficiency_down"));assert.ok(Array.isArray(payload.diagnostic_signals))});
test("invalid and empty AI responses fail validation",()=>{assert.equal(isAiInsightPayload(null),false);assert.equal(isAiInsightPayload({}),false);assert.equal(isAiInsightPayload({headline:"",executive_summary:"",performance_status:"mixed",key_insights:[],recommended_actions:[]}),false)});
test("normalizes the EDM insight framework",()=>{const insight={title:"Reach",summary:"Recipients increased.",evidence:"Recipients +20%",priority:"HIGH"},action={title:"Review flows",rationale:"Flows had the largest decline."};const result=parseAiInsightResponse(`Result:\n\`\`\`json\n${JSON.stringify({headline:"Revenue declined",summary:"Efficiency was lower.",performance_status:"NEGATIVE",overall_insights:[insight,insight,insight],whats_working:[insight],what_to_optimize:[insight],risks_to_watch:[insight],recommended_actions:[action,action,action]})}\n\`\`\``);assert.equal(result?.performance_status,"negative");assert.equal(result?.executive_summary,"Efficiency was lower.");assert.deepEqual(result?.overall_insights[0].evidence,["Recipients +20%"]);assert.equal(result?.recommended_actions[0].priority,"medium")});
test("provider fallback remains a valid PDF-shaped insight",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(isAiInsightPayload(buildDeterministicInsight(payload)),true)});
test("Chinese provider fallback remains valid and localized",()=>{const payload:any=buildAnalysisPayload(data,details),result=buildDeterministicInsight(payload,"zh");assert.equal(isAiInsightPayload(result),true);assert.match(result.headline,/EDM 收入/)});
