import assert from "node:assert/strict";
import test from "node:test";
import { buildAnalysisPayload, buildPerformanceIntelligence, driverDiagnosis, isAiInsightPayload, parseAiInsightResponse, validateAiInsightClaims } from "./klaviyo-analytics.ts";

const entity=(id:string,parentId:string,revenue:number,recipients:number,delivered:number,opens:number,clicks:number,conversions:number)=>({id,name:id,parentId,parentName:parentId,channel:"email",revenue,recipients,delivered,opens,clicks,conversions});
const data:any={range:{start:"2026-09-08",end:"2026-09-14"},comparison:{start:"2026-09-01",end:"2026-09-07"},comparisonLabel:"Previous period",timezone:"US/Eastern",dataUpdatedThrough:"2026-09-14",totals:{emailRecipients:0},health:{bounceRate:.01,previousBounceRate:.02,unsubscribeRate:.003,previousUnsubscribeRate:.003,spamRate:.001,previousSpamRate:.001}};
const details:any={campaignMessages:{current:[entity("campaign-a","campaign",200,120,100,50,10,4)],comparison:[entity("campaign-a","campaign",100,100,90,36,9,2),entity("campaign-b","campaign",50,50,45,20,5,1)]},flowMessages:{current:[entity("flow-a","flow",400,200,180,90,18,8)],comparison:[entity("flow-a","flow",600,200,180,90,18,12)]}};

test("period comparison and hierarchy do not double count",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(payload.executive.edm_revenue.current,600);assert.equal(payload.executive.edm_revenue.previous,750);assert.equal(payload.executive.edm_revenue.absolute_delta,-150);assert.equal(payload.executive.campaign_revenue.current,200);assert.equal(payload.executive.flow_revenue.current,400)});
test("uses consistent Klaviyo denominators",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(payload.funnel.email.open_rate.current_rate,140/280);assert.equal(payload.funnel.email.click_rate.current_rate,28/280);assert.equal(payload.funnel.email.conversion_rate.current_rate,12/320);assert.equal(payload.funnel.email.orders_per_recipient.current,12/320)});
test("division by zero is safe",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(payload.funnel.sms.open_rate.current_rate,null);assert.equal(payload.funnel.sms.revenue_per_click.current,0)});
test("drivers rank by absolute revenue delta and calculate signed contribution",()=>{const payload:any=buildAnalysisPayload(data,details);assert.equal(payload.drivers.message_decliners[0].name,"flow-a");assert.equal(payload.drivers.message_decliners[0].revenue_delta,-200);assert.equal(payload.drivers.message_decliners[0].delta_contribution_pct,200/150);assert.equal(payload.drivers.message_gainers[0].name,"campaign-a")});
test("diagnostic thresholds create deterministic signals",()=>{const payload:any=buildAnalysisPayload(data,details);assert.ok(payload.diagnostic_signals.includes("revenue_efficiency_down"));assert.ok(Array.isArray(payload.diagnostic_signals))});
test("invalid and empty AI responses fail validation",()=>{assert.equal(isAiInsightPayload(null),false);assert.equal(isAiInsightPayload({}),false);assert.equal(isAiInsightPayload({headline:"",executive_summary:"",performance_status:"mixed",key_insights:[],recommended_actions:[]}),false)});
test("normalizes the EDM insight framework",()=>{const insight={title:"Reach",summary:"Recipients increased.",evidence:"Recipients +20%",priority:"HIGH"},action={title:"Review flows",rationale:"Flows had the largest decline."};const result=parseAiInsightResponse(`Result:\n\`\`\`json\n${JSON.stringify({headline:"Revenue declined",summary:"Efficiency was lower.",performance_status:"NEGATIVE",overall_insights:[insight,insight,insight],whats_working:[insight],what_to_optimize:[insight],risks_to_watch:[insight],recommended_actions:[action,action,action]})}\n\`\`\``);assert.equal(result?.performance_status,"negative");assert.equal(result?.executive_summary,"Efficiency was lower.");assert.deepEqual(result?.key_insights[0].supporting_evidence,["Recipients +20%"]);assert.equal(result?.recommended_actions[0].priority,"medium")});
test("concentration uses total negative loss and excludes gainers",()=>{const payload:any=buildPerformanceIntelligence(data,details);assert.equal(payload.revenue_concentration.flow.total_negative_delta,200);assert.equal(payload.revenue_concentration.flow.top_1_loss_share,1);assert.equal(payload.revenue_concentration.flow.top_3_loss_share,1);assert.equal(payload.revenue_concentration.flow.concentration_level,"concentrated")});
test("funnel diagnosis compares efficiencies rather than raw volumes",()=>{const payload:any=buildPerformanceIntelligence(data,details),funnel=payload.funnel_diagnosis.email;assert.equal(funnel.delivery_rate.current,280/320);assert.equal(funnel.open_rate.current,140/280);assert.equal(funnel.click_to_open_rate.current,28/140);assert.equal(funnel.click_to_order_rate.current,12/28);assert.equal(funnel.revenue_per_order.current,600/12);assert.notEqual(funnel.largest_deterioration,"recipients")});
test("hypothesis checks expose evidence status and insufficient data",()=>{const payload:any=buildPerformanceIntelligence(data,details);assert.ok(["supported","contradicted","inconclusive"].includes(payload.hypothesis_checks.email.lower_reach_explains_revenue_decline.evidence_status));const empty:any={...details,campaignMessages:{current:[],comparison:[]},flowMessages:{current:[],comparison:[]}};const noData:any=buildPerformanceIntelligence(data,empty);assert.equal(noData.hypothesis_checks.email.lower_engagement_explains_revenue_decline.evidence_status,"inconclusive")});
test("old AI response schema normalizes at ingestion without polluting canonical output",()=>{const result=parseAiInsightResponse(JSON.stringify({headline:"Test",executive_summary:"Summary",performance_status:"mixed",overall_insights:[{title:"Old",finding:"Observed",evidence:["Evidence"],business_impact:"Impact",priority:"high"}],whats_working:[],what_to_optimize:[],risks_to_watch:[],recommended_actions:[{action:"Review",reason:"Because",priority:"medium"}]}));assert.equal(result?.key_insights[0].observation,"Observed");assert.deepEqual(result?.key_insights[0].supporting_evidence,["Evidence"]);assert.equal(result?.key_insights[0].business_implication,"Impact");assert.equal(result?.key_insights[0].confidence,"medium");assert.equal(result?.suggested_questions.length,5);assert.deepEqual(Object.keys(result||{}).sort(),["executive_summary","headline","key_insights","performance_status","recommended_actions","suggested_questions"])});


test("real driver patterns classify volume and downstream deterioration",()=>{
 const base=(revenue:number,recipients:number,open:number,click:number,conversion:number,rpr:number,aov:number)=>({revenue:{change_pct:revenue},recipients:{change_pct:recipients},open_rate:{delta_pp:open},click_rate:{delta_pp:click},conversion_rate:{delta_pp:conversion},revenue_per_recipient:{change_pct:rpr},aov:{change_pct:aov}});
 assert.equal(driverDiagnosis(base(-.673,-.673,1.65,1.87,0,.001,.085)).primary_driver,"volume_driven");
 assert.equal(driverDiagnosis(base(-.615,-.685,0,0,1.36,.223,.112)).primary_driver,"volume_driven");
 const mixed=driverDiagnosis(base(-.670,-.604,0,-1.71,-1.99,-.16757,.08034)); assert.equal(mixed.primary_driver,"volume_driven"); assert.ok(["efficiency_driven","conversion_driven"].includes(mixed.secondary_driver as string));
 const downstream=driverDiagnosis(base(-.991,-.531,1.54,1.03,-6.81,-.981,-.892)); assert.ok(["conversion_driven","aov_driven"].includes(downstream.primary_driver)); assert.notEqual(downstream.primary_driver,"insufficient_evidence");
 assert.match(String(driverDiagnosis(base(-.67,-.60,0,0,0,-.16757,.08034)).evidence.find((x:string)=>x.startsWith("rpr_change_pct="))||""),/-16\.8%/);
});
test("fact guardrails and claim validation catch factual reversals",()=>{const context:any=buildPerformanceIntelligence(data,details);assert.equal(context.fact_guardrails.email.recipients_direction,"decreased");assert.equal(context.fact_guardrails.campaign.comparison_available,true);const insight:any={headline:"Email reach increased",executive_summary:"Unique email opens increased.",performance_status:"negative",key_insights:[{title:"Reach",observation:"Email recipients were up.",interpretation:"Email reach increased.",supporting_evidence:[],driver:"volume_driven",business_implication:"Higher reach.",next_step:"Investigate.",confidence:"high"}],recommended_actions:[{action:"Investigate",reason:"Validate volume.",priority:"high"}]};assert.ok(validateAiInsightClaims(insight,context).some(error=>error.includes("Email recipients")));assert.ok(validateAiInsightClaims(insight,context).some(error=>error.includes("Unique email opens")))});
