import "server-only";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { connection } from "next/server";
import { resolveTestingPeriod, testingPeriodLabels, type TestingPeriodInput } from "@/lib/testing-google";

const API="https://ads-api.reddit.com/api/v3";const USER_AGENT="web:emw3-dashboard:1.0";
type Credentials={refresh_token:string;CLIENT_ID:string;CLIENT_SECRET:string;Ad_Account_ID:string};type ApiList<T>={data:T[]};type Campaign={id:string;name:string;objective:string;effective_status:string};type AdGroup={id:string;campaign_id:string;name:string;effective_status:string};type Ad={id:string;campaign_id:string;ad_group_id:string;name:string;post_id:string;post_url:string;effective_status:string};type Post={id:string;type:string;thumbnail_url?:string;post_url?:string;headline?:string;body?:string;content?:Array<{media_url?:string}>};
type RawMetric={campaign_id?:string;ad_group_id?:string;ad_id?:string;impressions?:number;clicks?:number;spend?:number;reach?:number;conversion_purchase_clicks?:number;conversion_purchase_views?:number;conversion_purchase_total_value?:number};
export type RedditMetrics={spend:number;impressions:number;clicks:number;reach:number;ctr:number|null;cpm:number|null;costPerThousandReach:number|null;orders:number;revenue:number;cpa:number|null;cvr:number|null;roas:number|null;cpc:number|null};
export type RedditAd=RedditMetrics&{adId:string;name:string;headline:string|null;body:string|null;contentType:"Image"|"Video"|"Message";thumbnailUrl:string|null;videoUrl:string|null;postUrl:string|null};
export type RedditGroup=RedditMetrics&{adGroupId:string;name:string;activeAds:RedditAd[]};
export type RedditCampaign=RedditMetrics&{campaignId:string;name:string;kind:"Awareness"|"Conversion";groups:RedditGroup[]};
export type RedditTestingData={period:{start:string;end:string};periodLabel:string;campaigns:RedditCampaign[]};
let tokenCache:{value:string;expires:number}|null=null;
async function credentials(){return JSON.parse(await readFile(path.join(process.cwd(),"credentials/reddit.json"),"utf8")) as Credentials;}
async function accessToken(){if(tokenCache&&tokenCache.expires>Date.now())return tokenCache.value;const c=await credentials();const response=await fetch("https://www.reddit.com/api/v1/access_token",{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${c.CLIENT_ID}:${c.CLIENT_SECRET}`).toString("base64")}`,"Content-Type":"application/x-www-form-urlencoded","User-Agent":USER_AGENT},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:c.refresh_token}),cache:"no-store"});const body=await response.json() as {access_token?:string;expires_in?:number};if(!response.ok||!body.access_token)throw new Error("Unable to refresh Reddit access token.");tokenCache={value:body.access_token,expires:Date.now()+Math.max(60,(body.expires_in??3600)-120)*1000};return body.access_token;}
async function reddit<T>(endpoint:string,init:RequestInit={}):Promise<T>{const response=await fetch(`${API}${endpoint}`,{...init,headers:{Authorization:`Bearer ${await accessToken()}`,"User-Agent":USER_AGENT,"Content-Type":"application/json",...(init.headers??{})},next:{revalidate:3600}});if(!response.ok)throw new Error(`Reddit API failed (${response.status}): ${(await response.text()).slice(0,300)}`);return response.json() as Promise<T>;}
const iso=(date:Date)=>date.toISOString().slice(0,10);const addDay=(value:string)=>{const date=new Date(`${value}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+1);return iso(date);};
function values(row:RawMetric={}):RedditMetrics{const spend=Number(row.spend??0)/1e6,impressions=Number(row.impressions??0),clicks=Number(row.clicks??0),reach=Number(row.reach??0),orders=Number(row.conversion_purchase_clicks??0)+Number(row.conversion_purchase_views??0),revenue=Number(row.conversion_purchase_total_value??0)/100;const ratio=(a:number,b:number)=>b>0?a/b:null;return {spend,impressions,clicks,reach,orders,revenue,ctr:ratio(clicks,impressions),cpm:ratio(spend*1000,impressions),costPerThousandReach:ratio(spend*1000,reach),cpa:ratio(spend,orders),cvr:ratio(orders,clicks),roas:ratio(revenue,spend),cpc:ratio(spend,clicks)};}
async function report(accountId:string,period:{start:string;end:string},breakdown:"CAMPAIGN_ID"|"AD_GROUP_ID"|"AD_ID"){const fields=["IMPRESSIONS","CLICKS","SPEND","REACH","CONVERSION_PURCHASE_CLICKS","CONVERSION_PURCHASE_VIEWS","CONVERSION_PURCHASE_TOTAL_VALUE"];const result=await reddit<{data:{metrics:RawMetric[]}}>(`/ad_accounts/${accountId}/reports`,{method:"POST",body:JSON.stringify({data:{starts_at:`${period.start}T00:00:00Z`,ends_at:`${addDay(period.end)}T00:00:00Z`,breakdowns:[breakdown],fields}})});return result.data.metrics;}
export async function getRedditTestingData(input:TestingPeriodInput={}):Promise<RedditTestingData>{await connection();const c=await credentials();const latest=iso(new Date(Date.now()-86400000));const preset=input.preset??"lastWeek",period=resolveTestingPeriod(latest,input);const [campaignList,groupList,adList,campaignRows,groupRows,adRows]=await Promise.all([reddit<ApiList<Campaign>>(`/ad_accounts/${c.Ad_Account_ID}/campaigns`),reddit<ApiList<AdGroup>>(`/ad_accounts/${c.Ad_Account_ID}/ad_groups`),reddit<ApiList<Ad>>(`/ad_accounts/${c.Ad_Account_ID}/ads`),report(c.Ad_Account_ID,period,"CAMPAIGN_ID"),report(c.Ad_Account_ID,period,"AD_GROUP_ID"),report(c.Ad_Account_ID,period,"AD_ID")]);const campaignsRaw=campaignList.data.filter(item=>item.effective_status==="ACTIVE"&&["IMPRESSIONS","CONVERSIONS"].includes(item.objective));const activeAds=adList.data.filter(item=>item.effective_status==="ACTIVE"&&campaignsRaw.some(campaign=>campaign.id===item.campaign_id));const postEntries=await Promise.all(activeAds.map(async ad=>{const result=await reddit<{data:Post}>(`/posts/${ad.post_id}`);return [ad.id,result.data] as const;}));const posts=new Map(postEntries);const adMetric=new Map(adRows.map(row=>[row.ad_id,row]));const groupMetric=new Map(groupRows.map(row=>[row.ad_group_id,row]));const campaignMetric=new Map(campaignRows.map(row=>[row.campaign_id,row]));const campaigns=campaignsRaw.map(campaign=>{const groups=groupList.data.filter(group=>group.campaign_id===campaign.id&&group.effective_status==="ACTIVE").map(group=>{const ads=activeAds.filter(ad=>ad.ad_group_id===group.id).map(ad=>{const post=posts.get(ad.id);const type=post?.type==="VIDEO"?"Video" as const:post?.type==="TEXT"?"Message" as const:"Image" as const;return {adId:ad.id,name:ad.name,headline:post?.headline?.trim()||null,body:post?.body?.trim()||null,contentType:type,thumbnailUrl:post?.thumbnail_url??null,videoUrl:type==="Video"?post?.content?.[0]?.media_url??null:null,postUrl:post?.post_url??ad.post_url??null,...values(adMetric.get(ad.id))};}).sort((a,b)=>b.spend-a.spend);return {adGroupId:group.id,name:group.name,activeAds:ads,...values(groupMetric.get(group.id))};}).sort((a,b)=>b.spend-a.spend);return {campaignId:campaign.id,name:campaign.name,kind:campaign.objective==="IMPRESSIONS"?"Awareness" as const:"Conversion" as const,groups,...values(campaignMetric.get(campaign.id))};}).sort((a,b)=>a.kind.localeCompare(b.kind));return {period,periodLabel:testingPeriodLabels[preset],campaigns};}
