import Link from "next/link";
import { RiArrowLeftLine, RiArrowRightLine, RiBarChartGroupedLine, RiFlaskLine, RiMailLine } from "@remixicon/react";
import { BluevuaMark, Emw3Logo } from "@/components/brand/emw3-logo";

export default function BluevuaProject() {
  return <main className="min-h-screen bg-background-secondary-default px-5 py-6 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="mb-8 flex items-center justify-between gap-4"><Link href="/" aria-label="Go to homepage"><Emw3Logo priority className="w-44 sm:w-52" /></Link><Link href="/" className="inline-flex items-center gap-2 text-body-medium text-text-secondary hover:text-text-primary"><RiArrowLeftLine className="size-4" aria-hidden /> All projects</Link></div><section className="rounded-3xl border border-border-button-default bg-background-primary-default p-6 shadow-card sm:p-8"><div className="flex items-center gap-4"><Link href="/" aria-label="Go to homepage"><BluevuaMark className="size-16 text-display-4-semibold" /></Link><div><p className="text-caption-1-semibold text-text-tertiary">PROJECT</p><h1 className="text-display-4-semibold text-text-primary">Bluevua</h1><p className="mt-1 text-body-regular text-text-secondary">Paid media performance workspace</p></div></div></section><section className="mt-10" aria-labelledby="dashboards-heading"><p className="text-caption-1-semibold text-text-tertiary">ANALYTICS</p><h2 id="dashboards-heading" className="mt-1 text-title-1-semibold text-text-primary">Dashboards</h2><div className="mt-5 grid gap-5"><DashboardLink href="/bluevua/google" icon={RiBarChartGroupedLine} title="Google Ads Dashboard" description="Account overview, channel efficiency, search demand, products, locations and creative performance." /><DashboardLink href="/bluevua/edm" icon={RiMailLine} title="EDM Dashboard" description="Email marketing performance and campaign reporting. The existing dashboard will be migrated into this workspace." /><DashboardLink href="/bluevua/testing" icon={RiFlaskLine} title="Testing Dashboard" description="Plan cross-channel creative tests, monitor experiment health, and turn results into clear decisions and learnings." /></div></section></div></main>;
}

function DashboardLink({href,icon:Icon,title,description}:{href:string;icon:typeof RiBarChartGroupedLine;title:string;description:string}) {
  return <Link href={href} className="group grid gap-6 rounded-3xl border border-border-button-default bg-background-primary-default p-6 shadow-card transition hover:border-border-button-hover md:grid-cols-[1fr_auto] md:items-center"><div className="flex items-start gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-background-secondary-default text-foreground-icon-primary"><Icon className="size-6" aria-hidden /></span><div><h3 className="text-title-2-semibold text-text-primary">{title}</h3><p className="mt-1 max-w-xl text-body-regular text-text-secondary">{description}</p></div></div><span className="flex items-center gap-2 text-body-medium text-button-ghost-foreground">Open dashboard <RiArrowRightLine className="size-5 transition-transform group-hover:translate-x-1" aria-hidden /></span></Link>;
}
