import type { DemandGenData } from "@/lib/testing-demand-gen";
import type { EdmTestingData } from "@/lib/testing-edm";
import type { GoogleSearchTest } from "@/lib/testing-google";
import type { MetaCampaignTest } from "@/lib/testing-meta";
import type { RedditTestingData } from "@/lib/testing-reddit";
import { cx } from "@/utils/cx";

type Metric={spend:number;revenue:number;orders:number;clicks:number};
type Segment={label:string;value:number;display:string;color:string;dot:string};
const channelStyle={Google:{color:"stroke-chart-4",dot:"bg-chart-4"},Meta:{color:"stroke-chart-5",dot:"bg-chart-5"},Reddit:{color:"stroke-chart-3",dot:"bg-chart-3"},EDM:{color:"stroke-chart-8",dot:"bg-chart-8"}};
const assetStyle={Message:{color:"stroke-chart-2",dot:"bg-chart-2"},Picture:{color:"stroke-chart-3",dot:"bg-chart-3"},Video:{color:"stroke-chart-5",dot:"bg-chart-5"}};
const currency=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}),number=new Intl.NumberFormat("en-US",{maximumFractionDigits:0}),percent=new Intl.NumberFormat("en-US",{style:"percent",minimumFractionDigits:2,maximumFractionDigits:2});
const empty=():Metric=>({spend:0,revenue:0,orders:0,clicks:0});
const add=(target:Metric,row:Metric)=>{target.spend+=row.spend;target.revenue+=row.revenue;target.orders+=row.orders;target.clicks+=row.clicks;};
const ratio=(a:number,b:number)=>b>0?a/b:null;
const showRatio=(value:number|null,suffix="")=>value==null?"—":`${value.toFixed(2)}${suffix}`;

function SegmentedGauge({segments,value,caption}:{segments:Segment[];value:string;caption:string}){const total=segments.reduce((sum,item)=>sum+Math.max(0,item.value),0),gap=segments.length>1?1.5:0;let offset=0;return <div><div className="relative mx-auto h-36 max-w-sm"><svg viewBox="0 0 180 110" className="size-full" aria-hidden><path d="M 20 92 A 70 70 0 0 1 160 92" pathLength="100" fill="none" className="stroke-chart-track" strokeWidth="14" strokeLinecap="round"/>{segments.map(item=>{const share=total?item.value/total*100:0,start=offset;offset+=share;return <path key={item.label} d="M 20 92 A 70 70 0 0 1 160 92" pathLength="100" fill="none" className={item.color} strokeWidth="14" strokeLinecap="round" strokeDasharray={`${Math.max(0,share-gap)} ${100-Math.max(0,share-gap)}`} strokeDashoffset={-start}/>;})}</svg><div className="absolute inset-x-0 bottom-1 text-center"><p className="text-title-1-medium tabular-nums text-text-primary">{value}</p><p className="text-caption-2-regular text-text-tertiary">{caption}</p></div></div><div className="mt-2 flex flex-wrap justify-center gap-x-4 gap-y-2">{segments.map(item=><span key={item.label} className="inline-flex items-center gap-1.5 text-body-2-regular text-text-secondary"><span className={cx("size-2.5 rounded-full",item.dot)}/>{item.label} <strong className="text-body-2-medium text-text-primary">{item.display}</strong></span>)}</div></div>;}

function MetricCard({title,value,caption,segments,children,className}:{title:string;value:string;caption:string;segments:Segment[];children?:React.ReactNode;className?:string}){return <article className={cx("rounded-3xl border border-border-button-default bg-background-primary-default p-5 shadow-card",className)}><h3 className="text-title-3-semibold text-text-primary">{title}</h3><SegmentedGauge segments={segments} value={value} caption={caption}/>{children}</article>;}
function DetailRow({title,items}:{title:string;items:Segment[]}){return <div className="mt-5 border-t border-separator-border pt-4"><p className="text-caption-1-semibold text-text-tertiary">{title}</p><div className="mt-3 flex flex-wrap gap-2">{items.map(item=><span key={item.label} className="inline-flex items-center gap-1.5 rounded-full bg-background-secondary-default px-3 py-1.5 text-caption-1-semibold text-text-secondary"><span className={cx("size-2 rounded-full",item.dot)}/>{item.label}<span className="text-text-primary">{item.display}</span></span>)}</div></div>;}

export function BusinessPerformance({google,demandGen,meta,reddit,edm}:{google:GoogleSearchTest;demandGen:DemandGenData;meta:MetaCampaignTest;reddit:RedditTestingData;edm:EdmTestingData}){
  const channels:Record<keyof typeof channelStyle,Metric>={Google:empty(),Meta:empty(),Reddit:empty(),EDM:empty()};
  google.groups.forEach(row=>add(channels.Google,row));demandGen.campaigns.forEach(row=>add(channels.Google,row));add(channels.Meta,meta.totals);reddit.campaigns.forEach(row=>add(channels.Reddit,row));edm.tests.forEach(row=>add(channels.EDM,{spend:0,revenue:row.revenue,orders:row.orders,clicks:row.clicks}));
  const assetCounts={Message:google.groups.length+edm.tests.length,Picture:demandGen.campaigns.filter(row=>row.mediaType==="image").reduce((sum,row)=>sum+row.groups.length,0),Video:demandGen.campaigns.filter(row=>row.mediaType==="video").reduce((sum,row)=>sum+row.groups.length,0)};
  const assetMetrics:Record<keyof typeof assetStyle,Metric>={Message:empty(),Picture:empty(),Video:empty()},paidAssetMetrics:Record<keyof typeof assetStyle,Metric>={Message:empty(),Picture:empty(),Video:empty()};
  const assetRows:Array<Metric&{type:keyof typeof assetStyle;paid:boolean}>=[];
  google.groups.forEach(row=>assetRows.push({...row,type:"Message",paid:true}));
  demandGen.campaigns.forEach(row=>assetRows.push({...row,type:row.mediaType==="image"?"Picture":"Video",paid:true}));
  meta.adGroups.flatMap(group=>group.activeAds).forEach(row=>{assetCounts[row.mediaType==="Image"?"Picture":"Video"]++;assetRows.push({...row,type:row.mediaType==="Image"?"Picture":"Video",paid:true});});
  reddit.campaigns.flatMap(campaign=>campaign.groups).flatMap(group=>group.activeAds).forEach(row=>{const type=row.contentType==="Image"?"Picture":row.contentType==="Video"?"Video":"Message";assetCounts[type]++;assetRows.push({...row,type,paid:true});});
  edm.tests.forEach(row=>assetRows.push({spend:0,revenue:row.revenue,orders:row.orders,clicks:row.clicks,type:"Message",paid:false}));
  assetRows.forEach(row=>{add(assetMetrics[row.type],row);if(row.paid)add(paidAssetMetrics[row.type],row);});
  const all=Object.values(channels).reduce((sum,row)=>(add(sum,row),sum),empty());
  const averageCvr=(()=>{const values=assetRows.filter(row=>row.clicks>0).map(row=>row.orders/row.clicks);return values.length?values.reduce((a,b)=>a+b,0)/values.length:null;})();
  const channelSegments=(metric:"revenue"|"orders",formatter:(value:number)=>string):Segment[]=>(Object.keys(channelStyle) as Array<keyof typeof channelStyle>).map(label=>({label,value:channels[label][metric],display:formatter(channels[label][metric]),...channelStyle[label]}));
  const channelRoas:Segment[]=(Object.keys(channelStyle) as Array<keyof typeof channelStyle>).map(label=>({label,value:channels[label].spend,display:showRatio(ratio(channels[label].revenue,channels[label].spend)),...channelStyle[label]}));
  const channelCvr:Segment[]=(Object.keys(channelStyle) as Array<keyof typeof channelStyle>).map(label=>({label,value:channels[label].clicks,display:channels[label].clicks?percent.format(channels[label].orders/channels[label].clicks):"—",...channelStyle[label]}));
  const assetRoas:Segment[]=(Object.keys(assetStyle) as Array<keyof typeof assetStyle>).map(label=>({label,value:paidAssetMetrics[label].spend,display:showRatio(ratio(paidAssetMetrics[label].revenue,paidAssetMetrics[label].spend)),...assetStyle[label]}));
  const assetCvr:Segment[]=(Object.keys(assetStyle) as Array<keyof typeof assetStyle>).map(label=>({label,value:assetMetrics[label].clicks,display:assetMetrics[label].clicks?percent.format(assetMetrics[label].orders/assetMetrics[label].clicks):"—",...assetStyle[label]}));
  const countSegments:Segment[]=(Object.keys(assetStyle) as Array<keyof typeof assetStyle>).map(label=>({label,value:assetCounts[label],display:number.format(assetCounts[label]),...assetStyle[label]}));
  return <section aria-labelledby="overview-metrics"><h2 id="overview-metrics" className="text-title-2-semibold text-text-primary">Business Performance</h2><div className="mt-4 grid gap-4 lg:grid-cols-6"><MetricCard title="Total Number of Assets" value={number.format(Object.values(assetCounts).reduce((a,b)=>a+b,0))} caption="Tested assets" segments={countSegments} className="lg:col-span-2"/><MetricCard title="Total Revenue" value={currency.format(all.revenue)} caption="Attributed revenue" segments={channelSegments("revenue",currency.format)} className="lg:col-span-2"/><MetricCard title="Total Orders" value={number.format(all.orders)} caption="Attributed orders" segments={channelSegments("orders",number.format)} className="lg:col-span-2"/><MetricCard title="Total ROAS" value={showRatio(ratio(all.revenue,all.spend))} caption="Total revenue / total cost" segments={channelRoas} className="lg:col-span-3"><DetailRow title="BY ASSET TYPE" items={assetRoas}/></MetricCard><MetricCard title="Total Conversion Rate" value={averageCvr==null?"—":percent.format(averageCvr)} caption="Average asset conversion rate" segments={channelCvr} className="lg:col-span-3"><DetailRow title="BY ASSET TYPE" items={assetCvr}/></MetricCard></div></section>;
}
