import Image from "next/image";
import Link from "next/link";
import { RiImageLine, RiPlayCircleLine } from "@remixicon/react";
import { Chip } from "@/components/base/badges/chip";
import type { DemandGenData, DemandGenMetricRow } from "@/lib/testing-demand-gen";

const currency=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});const decimal=new Intl.NumberFormat("en-US",{maximumFractionDigits:2});const percent=new Intl.NumberFormat("en-US",{style:"percent",minimumFractionDigits:2,maximumFractionDigits:2});
const columns:Array<{label:string;value:(row:DemandGenMetricRow)=>string}>=[{label:"CPA",value:row=>row.cpa==null?"—":currency.format(row.cpa)},{label:"CVR",value:row=>row.cvr==null?"—":percent.format(row.cvr)},{label:"ROAS",value:row=>row.roas==null?"—":row.roas.toFixed(2)},{label:"Orders",value:row=>decimal.format(row.orders)},{label:"Revenue",value:row=>currency.format(row.revenue)},{label:"Spend",value:row=>currency.format(row.spend)},{label:"CTR",value:row=>row.ctr==null?"—":percent.format(row.ctr)},{label:"CPC",value:row=>row.cpc==null?"—":currency.format(row.cpc)}];
const date=(value:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));

export function DemandGenSection({data,query=""}:{data:DemandGenData;query?:string}){
  return <section className="mt-8"><div className="grid gap-6">{data.campaigns.map(campaign=><article key={campaign.key} className="overflow-hidden rounded-3xl border border-border-button-default bg-background-primary-default shadow-card">
    <div className="flex flex-col gap-4 border-b border-border-table p-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-background-secondary-default text-foreground-icon-primary">{campaign.mediaType==="image"?<RiImageLine className="size-5" aria-hidden/>:<RiPlayCircleLine className="size-5" aria-hidden/>}</span><div><div className="flex items-center gap-1.5 text-caption-1-semibold text-text-tertiary"><span>GOOGLE ·</span><Chip variant="caption" color="purple">DEMAND GEN</Chip><span>CAMPAIGN</span></div><h2 className="mt-1 break-words text-title-2-semibold text-text-primary">{campaign.campaignName}</h2><p className="mt-1 text-body-regular text-text-secondary">{campaign.title}</p></div></div>{data.period&&<p className="rounded-xl bg-background-secondary-default px-3 py-2 text-body-medium text-text-secondary">{data.periodLabel} · {date(data.period.start)} – {date(data.period.end)}</p>}</div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1080px] border-collapse"><thead><tr className="border-b border-border-table text-left text-caption-1-semibold text-text-tertiary"><th className="px-5 py-3">Ad group</th>{columns.map(column=><th key={column.label} className="px-4 py-3 text-right">{column.label}</th>)}</tr></thead><tbody>{campaign.groups.map(group=>{const href=`/bluevua/testing/google/demand-gen/${campaign.key}/${group.label==="Group A"?"a":"b"}${query?`?${query}`:""}`;return <tr key={group.label} className="border-b border-border-table last:border-0 hover:bg-background-primary-hover"><td className="px-5 py-3"><Link href={href} className="flex min-w-80 items-center gap-4 text-text-primary hover:text-button-ghost-foreground"><span className="relative flex size-16 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-background-secondary-default">{campaign.previewUrl?<Image src={campaign.previewUrl} alt={campaign.adGroupName} fill sizes="160px" className="object-cover"/>:campaign.mediaType==="image"?<RiImageLine className="size-6 text-foreground-icon-tertiary" aria-hidden/>:<RiPlayCircleLine className="size-7 text-foreground-icon-tertiary" aria-hidden/>}</span><span className="text-body-medium">{group.label} · {campaign.adGroupName}</span></Link></td>{columns.map(column=><td key={column.label} className="px-4 py-4 text-right text-body-medium tabular-nums text-text-primary">{column.value(campaign)}</td>)}</tr>})}</tbody></table></div>
  </article>)}</div></section>;
}
