import { RiSearchLine } from "@remixicon/react";
import { Chip } from "@/components/base/badges/chip";
import type { GoogleSearchTest, GoogleTestGroup } from "@/lib/testing-google";

const currency = new Intl.NumberFormat("en-US", {style:"currency",currency:"USD",maximumFractionDigits:0});
const decimal = new Intl.NumberFormat("en-US", {maximumFractionDigits:2});
const percent = new Intl.NumberFormat("en-US", {style:"percent",minimumFractionDigits:2,maximumFractionDigits:2});
const columns: Array<{label:string;key:keyof GoogleTestGroup;format:"currency"|"decimal"|"percent"|"roas";primary?:boolean}> = [
  {label:"CPA",key:"cpa",format:"currency",primary:true},{label:"CVR",key:"cvr",format:"percent",primary:true},{label:"ROAS",key:"roas",format:"roas",primary:true},{label:"Orders",key:"orders",format:"decimal"},{label:"Revenue",key:"revenue",format:"currency"},{label:"Spend",key:"spend",format:"currency"},{label:"CTR",key:"ctr",format:"percent"},{label:"CPC",key:"cpc",format:"currency"},
];

function metric(value:number|null, format:"currency"|"decimal"|"percent"|"roas") { if(value==null||!Number.isFinite(value))return "—";if(format==="currency")return currency.format(value);if(format==="percent")return percent.format(value);if(format==="roas")return value.toFixed(2);return decimal.format(value); }
function displayDate(value:string) { return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)); }

export function GoogleTestSection({test,compact=false}:{test:GoogleSearchTest;compact?:boolean}) {
  return <section className="rounded-3xl border border-border-button-default bg-background-primary-default shadow-card"><div className="flex flex-col gap-4 border-b border-border-table p-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-background-secondary-default text-foreground-icon-primary"><RiSearchLine className="size-5" aria-hidden /></span><div><div className="flex items-center gap-1.5 text-caption-1-semibold text-text-tertiary"><span>GOOGLE ·</span><Chip variant="caption" color="blue">SEARCH</Chip><span>CAMPAIGN</span></div><h2 className="mt-1 text-title-2-semibold text-text-primary">{test.campaignName}</h2><p className="mt-1 text-body-regular text-text-secondary">Group A test vs. Group B control</p></div></div>{test.period&&<div className="rounded-xl bg-background-secondary-default px-3 py-2 text-body-medium text-text-secondary">{test.periodLabel} · {displayDate(test.period.start)} – {displayDate(test.period.end)}</div>}</div>{test.groups.length?<div className="overflow-x-auto"><table className="w-full min-w-[1050px] border-collapse"><thead><tr className="border-b border-border-table text-left text-caption-1-semibold text-text-tertiary"><th className="px-5 py-3">Ad group</th>{columns.map(column=><th key={column.label} className="px-4 py-3 text-right">{column.label}{column.primary&&!compact&&<span className="ml-1 text-text-placeholder">Primary</span>}</th>)}</tr></thead><tbody>{test.groups.map(group=><tr key={group.adGroupId} className="border-b border-border-table last:border-0 hover:bg-background-primary-hover"><td className="px-5 py-4"><p className="text-body-medium text-text-primary">{group.label} · {group.name}</p><p className="mt-1 text-caption-2-regular text-text-tertiary">{group.label==="Group A"?"Test":"Control"}</p></td>{columns.map(column=><td key={column.label} className="px-4 py-4 text-right text-body-medium tabular-nums text-text-primary">{metric(group[column.key] as number|null,column.format)}</td>)}</tr>)}</tbody></table></div>:<p className="p-6 text-body-regular text-text-secondary">No ad group performance is available for this campaign.</p>}</section>;
}
