import Link from "next/link";
import { RiRedditLine } from "@remixicon/react";
import { Chip } from "@/components/base/badges/chip";
import { ImageLightbox } from "@/components/application/media/image-lightbox";
import type { RedditMetrics, RedditTestingData } from "@/lib/testing-reddit";
type RedditCampaign=RedditMetrics;

const currency=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2});const percent=new Intl.NumberFormat("en-US",{style:"percent",minimumFractionDigits:2,maximumFractionDigits:2});const decimal=new Intl.NumberFormat("en-US",{maximumFractionDigits:2});
const date=(value:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));
function value(campaign:RedditMetrics,key:string){const raw=campaign[key as keyof RedditMetrics] as number|null;if(raw==null||!Number.isFinite(raw))return "—";if(["ctr","cvr"].includes(key))return percent.format(raw);if(key==="roas")return raw.toFixed(2);if(["orders"].includes(key))return decimal.format(raw);return currency.format(raw);}
const labels={Awareness:[{key:"ctr",label:"CTR"},{key:"cpm",label:"CPM"},{key:"costPerThousandReach",label:"Cost / 1K reach"},{key:"spend",label:"Spend"}],Conversion:[{key:"cpa",label:"CPA"},{key:"cvr",label:"CVR"},{key:"roas",label:"ROAS"},{key:"orders",label:"Orders"},{key:"revenue",label:"Revenue"},{key:"spend",label:"Spend"},{key:"ctr",label:"CTR"},{key:"cpc",label:"CPC"},{key:"cpm",label:"CPM"}]};

export function RedditCampaignSection({data,query=""}:{data:RedditTestingData;query?:string}){return <section className="mt-8 grid gap-6">{data.campaigns.map(campaign=><article key={campaign.campaignId} className="overflow-hidden rounded-3xl border border-border-button-default bg-background-primary-default shadow-card"><div className="flex flex-col gap-4 border-b border-border-table p-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-status-rose-background text-status-rose-text"><RiRedditLine className="size-5" aria-hidden/></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-1.5 text-caption-1-semibold text-text-tertiary"><span>REDDIT ·</span><Chip variant="caption" color={campaign.kind==="Awareness"?"rose":"purple"}>{campaign.kind.toUpperCase()}</Chip><span>CAMPAIGN</span></div><h2 className="mt-1 break-words text-title-2-semibold text-text-primary">{campaign.name}</h2><p className="mt-1 text-body-regular text-text-secondary">{campaign.kind==="Awareness"?"Picture and video awareness performance":"Picture and video conversion performance"}</p></div></div><p className="shrink-0 rounded-xl bg-background-secondary-default px-3 py-2 text-body-medium text-text-secondary">{data.periodLabel} · {date(data.period.start)} – {date(data.period.end)}</p></div><div>{campaign.groups.map(group=>{const cover=group.activeAds[0],href=`/bluevua/testing/reddit/${group.adGroupId}${query?`?${query}`:""}`;return <div key={group.adGroupId} className="grid gap-5 border-b border-border-table p-5 last:border-0 hover:bg-background-primary-hover lg:grid-cols-[minmax(260px,2fr)_minmax(420px,3fr)] lg:items-center"><div className="flex min-w-0 items-center gap-4"><ImageLightbox src={cover?.thumbnailUrl??null} alt={group.name}/><div className="min-w-0"><Link href={href} className="block break-words text-body-medium text-text-primary hover:text-button-ghost-foreground">{group.name}</Link><p className="mt-1 text-caption-2-regular text-text-tertiary">{group.activeAds.length} active ads</p></div></div><dl className={`grid grid-cols-2 gap-x-4 gap-y-3 ${campaign.kind==="Awareness"?"lg:grid-cols-4":"lg:grid-cols-5"}`}>{labels[campaign.kind].map(item=><div key={item.key}><dt className="text-caption-1-semibold text-text-tertiary">{item.label}</dt><dd className="mt-1 text-body-medium tabular-nums text-text-primary">{value(group as RedditCampaign,item.key)}</dd></div>)}</dl></div>})}</div></article>)}</section>;}
